config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    delete "sign_out", to: "devise/sessions#destroy", as: :destroy_user_session
  end
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks",
    sessions: "sessions"
  }

  resources :daily_reports
  resources :tasks
  resources :task_logs, only: [:create]
end

app/models/daily_report.rb
class DailyReport < ActiveRecord::Base

  belongs_to :user

  validates :user_id, presence: true
  validates :date, presence: true

end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, scope: :provider

  def self.find_for_oauth(auth)
    identity = find_or_create_by(uid: auth.uid, provider: auth.provider)
    identity.update_attribute(:name, auth.info.nickname)
    identity
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  include AASM
  enum status: { yet: 0, doing: 1, done: 2, suspending: 3 }
  aasm column: :status, enum: true do
    state :yet, initial: true
    state :doing
    state :done
    state :suspending

    event :start, before: :before_start do
      transitions from: :yet, to: :doing
      transitions from: :suspending, to: :doing
    end

    event :pause do
      transitions from: :doing, to: :suspending
    end
  end

  validates :subject, presence: true
  has_many :task_logs
  belongs_to :user

  scope :by_user, ->(user) { where(user: user) }
  scope :waiting, -> { where.not(status: statuses[:doing]) }

  def start_task!(user)
    log = TaskLog.new(task_id: self.id, user_id: user.id)
    log.start_task!

  end

  # @return [Task] 対象者が持つdoingタスク
  def self.doing_of(user)
    Task.doing.find_by(user: user)
  end

  private def before_start
    # 同じユーザが持つタスクのdoingを無くす
    tasks = Task.where(user: self.user).doing
    tasks.each {|task| task.pause! }
  end

end

app/models/task_log.rb
class TaskLog < ActiveRecord::Base

  belongs_to :task

  def start_task!
    self.started_at = Time.zone.now
    self.task.start!
    self.save!
  end

  def stop_task
    self.task.pause!
  end

  def finished?
    self.finished_at.present?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :registerable, :rememberable, :trackable,
    :omniauthable, omniauth_providers: [:twitter]

  has_one :identity
  has_many :daily_reports

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy]
  before_action :set_daily_report, only: [:show, :edit, :update, :destroy]

  # GET /daily_reports
  # GET /daily_reports.json
  def index
    @daily_reports = DailyReport.all
  end

  # GET /daily_reports/1
  # GET /daily_reports/1.json
  def show
  end

  # GET /daily_reports/new
  def new
    @daily_report = DailyReport.new(date: DateTime.now)
  end

  # GET /daily_reports/1/edit
  def edit
  end

  # POST /daily_reports
  # POST /daily_reports.json
  def create
    @daily_report = DailyReport.new(daily_report_params)
    @daily_report.user_id = current_user.id

    respond_to do |format|
      if @daily_report.save
        format.html { redirect_to @daily_report, notice: 'Daily report was successfully created.' }
        format.json { render :show, status: :created, location: @daily_report }
      else
        format.html { render :new }
        format.json { render json: @daily_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_reports/1
  # PATCH/PUT /daily_reports/1.json
  def update
    respond_to do |format|
      if @daily_report.update(daily_report_params)
        format.html { redirect_to @daily_report, notice: 'Daily report was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_report }
      else
        format.html { render :edit }
        format.json { render json: @daily_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_reports/1
  # DELETE /daily_reports/1.json
  def destroy
    @daily_report.destroy
    respond_to do |format|
      format.html { redirect_to daily_reports_url, notice: 'Daily report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_report
      @daily_report = DailyReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_report_params
      params.require(:daily_report).permit(:date, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    generic_callback('twitter')
  end

  # ref. http://willschenk.com/setting-up-devise-with-twitter-and-facebook-and-other-omniauth-schemes-without-email-addresses/
  def generic_callback(provider)
    auth = env["omniauth.auth"]
    @identity = Identity.find_for_oauth(auth)
    @user = @identity.user || current_user

    if @user.nil?
      @user = User.create(name: auth.info.name, image: auth.info.image)
      @identity.update_attribute(:user_id, @user.id)
    end

    if @user.persisted?
      @identity.update_attribute(:user_id, @user.id)
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/task_logs_controller.rb
class TaskLogsController < ApplicationController

  def create
    task_log = TaskLog.new(task_log_params)
    if task_log.start_task!
      redirect_to tasks_path, notice: 'Task log was successfully created.'
    else
      redirect_to tasks_path, error: 'failed create task_log.'
    end
  end

  private def task_log_params
    params.require(:task_log).permit(:task_id, :user_id)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_tasks, only: [:index, :create]

  # GET /tasks
  # GET /tasks.json
  def index
    @task = Task.new
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to action: "index", notice: 'Task was successfully created.' }
        format.json { render :index, status: :created, location: @task }
      else
        format.html { render :index }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  private def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  private def task_params
    params.require(:task).permit(:subject, :status, :estimate_hours, :user_id)
  end

  # 表示用tasksを準備する
  private def set_tasks
    user_tasks = Task.by_user(current_user).order(created_at: :desc)
    @waiting_tasks = user_tasks.waiting
    @doing_tasks = user_tasks.doing
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/task_log_helper.rb
module TaskLogHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/views/daily_reports/_form.html.slim
= form_for @daily_report do |f|
  - if @daily_report.errors.any?
    #error_explanation
      h2 = "#{pluralize(@daily_report.errors.count, "error")} prohibited this daily_report from being saved:"
      ul
        - @daily_report.errors.full_messages.each do |message|
          li = message
  .form-group
    = f.label :date
    = f.text_field :date, class: "form-control"
  .form-group
    = f.label :body
    = f.text_field :body, class: "form-control"
  .actions
    = f.submit class: "btn btn-default"

javascript:
  $('#daily_report_date').datepicker();

app/views/daily_reports/edit.html.slim
h1 Editing daily_report

== render 'form'

= link_to 'Show', @daily_report
'|
= link_to 'Back', daily_reports_path

app/views/daily_reports/index.html.slim
h1 Listing daily_reports

table.table
  thead
    tr
      th Date
      th Body
      th User
      th
      th
      th

  tbody
    - @daily_reports.each do |daily_report|
      tr
        td = daily_report.date
        td = daily_report.body
        td = daily_report.user_id
        td = link_to 'Show', daily_report
        td = link_to 'Edit', edit_daily_report_path(daily_report)
        td = link_to 'Destroy', daily_report, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Daily report', new_daily_report_path, class: "btn btn-default"

app/views/daily_reports/new.html.slim
h1 New daily_report

== render 'form'

= link_to 'Back', daily_reports_path

app/views/daily_reports/show.html.slim
p#notice = notice

p
  strong Date:
  = @daily_report.date
p
  strong Body:
  = @daily_report.body
p
  strong User:
  = @daily_report.user_id

= link_to 'Edit', edit_daily_report_path(@daily_report)
'|
= link_to 'Back', daily_reports_path

app/views/home/_user_content.html.slim
h2 あなたの日報一覧
p
  = link_to '新しい日報を書く', new_daily_report_path, class: "btn btn-default"

table.table
  tr
    td 日付
    td 何をしたか
  - current_user.daily_reports.each do |report|
    tr
      td = report.date.strftime("%F")
      td = report.body

app/views/home/index.html.slim
- unless signed_in?
  = link_to "Twitterログイン", user_omniauth_authorize_path(:twitter), class: "btn btn-default"
- else
  = render "home/user_content"
  div
    = link_to "daily_reports一覧", daily_reports_path, class: "btn btn-default"
    = link_to "tasks一覧", tasks_path, class: "btn btn-default"
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-default"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Dailyreport
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .container
      h1 = link_to "日報", root_path
      - if signed_in?
        div
          = image_tag current_user.image, size: "24x24", alt: "#{current_user.name} さん"
          |#{current_user.name} さん
    - if flash.present?
      .container
        = flash[:success] || flash[:alert] || flash[:notice]
    .container
      = yield

app/views/tasks/_form.html.slim
= form_for @task, html: {class: "form-inline"} do |f|
  - if @task.errors.any?
    #error_explanation
      h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.full_messages.each do |message|
          li = message

  = f.hidden_field :user_id, value: current_user.try(:id)
  .form-group
    = f.label :subject
    = f.text_field :subject, class: "form-control"
  /.field
    = f.label :status
    = f.select :status, Task.statuses.keys.to_a, {}
    /= f.number_field :status
  .form-group
    = f.label :estimate_hours
    = f.text_field :estimate_hours, class: "form-control"
  = f.submit class: "btn btn-default"

app/views/tasks/_oneline.html.slim
tr
  td = task.subject
  td = render "/tasks/status", task: task
  td = task.estimate_hours
  td
    = form_for TaskLog.new do |f|
      = f.hidden_field :task_id, value: task.id
      = f.hidden_field :user_id, value: current_user.try(:id)
      = f.submit
  td = link_to 'Show', task
  td = link_to 'Edit', edit_task_path(task)
  td = link_to 'Destroy', task, data: {:confirm => 'Are you sure?'}, :method => :delete
- task.task_logs.each do |task_log|
  tr
    td
    td 開始#{task_log.started_at}
    td = "終了#{task_log.finished_at}" if task_log.finished?
    td = "経過時間#{task_log.spent_hours}" if task_log.finished?

app/views/tasks/_status.html.slim
- if task.doing?
  .label.label-doing = task.status
- elsif task.yet?
  .label.label-yet = task.status
- else
  .label.label-done = task.status

app/views/tasks/edit.html.slim
h1 Editing task

== render 'form'

= link_to 'Show', @task
'|
= link_to 'Back', tasks_path

app/views/tasks/index.html.slim
h1 Listing tasks

= render "tasks/form"

table.table
  thead
    tr
      th Subject
      th Status
      th Estimate hours
      th
      th
      th
      th

  tbody
    - @doing_tasks.each do |task|
      = render "/tasks/oneline", task: task
    - @waiting_tasks.each do |task|
      = render "/tasks/oneline", task: task

br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.slim
h1 New task

== render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.slim
p#notice = notice

p
  strong Status:
  = @task.status
p
  strong Estimate hours:
  = @task.estimate_hours

= link_to 'Edit', edit_task_path(@task)
'|
= link_to 'Back', tasks_path